/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  community: [
    // {
    //   type: 'autogenerated',
    //   dirName: '.',
    // },
    { type: 'doc', id: 'support' },
    { type: 'doc', id: 'how-to-contribute' },
    { type: 'doc', id: 'governance' },
    { type: 'doc', id: 'team' },
    // { type: 'doc', id: 'resources' },
    // { type: 'doc', id: 'contributing' },
    // {
    //   type: 'link',
    //   href: '/changelog',
    //   label: 'Changelog',
    // },
    // {
    //   type: 'link',
    //   href: '/feature-requests',
    //   label: 'Feature Requests',
    // },
    {
      type: 'link',
      label: 'Chat with us on Slack',
      href: 'http://t.uber.com/cadence-slack',
    },
    {
      type: 'link',
      label: 'Code of Conduct',
      href: 'https://github.com/uber/.github/blob/dcd96c52f2d1d839208315a2572cf37f48e52e96/CODE_OF_CONDUCT.md',
    },
  ],
};
